baseurl = "http://ryanking.com"
title = "Programming with a LISP"
copyright = "&copy; 2016 Ryan King"
languageCode = "en-us"
theme = "academic"
disqusShortname = "ryanking.disqus.com"

[params]
name = "Ryan King"
role = "Student of Computer Science"
organization = "Boston University"
email = "hello@ryanking.com"
phone = "(908) 256-9165"

date_format = "Mon, Jan 21, 1996"

math = false

sharing = false

custom_css = []
custom_js = []

[params.about]
interests = ["Functional Programming", "Machine Learning", "Computational Audio", "Graphic Design", "Web Development"]
str_interests = "Interests"
str_education = "Education"

[[params.about.education]]
course = "Accelerated MS/BA in Computer Science"
institution = "Boston University"
year = "2018"

[[params.about.education]]
course = "High School Diploma"
institution = "Bridgewater-Raritan High School"
year = "2014"

[[params.about.education]]
course = "Cisco Certification"
institution = "Somerset County Vocational & Technical High School"
year = "2012"

[params.publications]
count = 10
detailed_list = false
title = "Recent Publications"
subtitle = ""
str_all = "More Publications"

# Posts section.
# Section will only be displayed if there are posts in `content/post/`.
[params.posts]
count = 5
title = "Recent Posts"
subtitle = ""
str_all = "More Posts"
str_read_more = "Read more"

# Projects section.
# Section will only be displayed if there are projects in `content/project/`.
[params.projects]
title = "Projects"
subtitle = ""

# Contact section.
[params.contact]
enable = true
title = "Contact"
subtitle = ""
autolink = true  # Automatically link email and phone?


[[params.social]]
icon = "envelope"
icon_pack = "fa"
link = "mailto:hello@eryanking.com"

[[params.social]]
icon = "twitter"
icon_pack = "fa"
link = "//twitter.com/RyanKing"

[[params.social]]
icon = "github"
icon_pack = "fa"
link = "//github.com/RyanTKing"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
name = "Home"
url = "#top"
weight = 1

[[menu.main]]
name = "Publications"
url = "#publications"
weight = 2

[[menu.main]]
name = "Posts"
url = "#posts"
weight = 3

[[menu.main]]
name = "Projects"
url = "#projects"
weight = 4

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6