baseurl = "http://ryanking.com/"
languageCode = "en-us"
theme = "future-imperfect"
title = "The Website of Ryan King"
preserveTaxonomyNames = true
paginate = 3
copyright = "&copy; 2016 Ryan King"
disqusShortname = "carelesslisper"

[params]
description = "The rantings and ravings of a computer science student with an affinity for obscure programming languages"
navbarTitle = "RyanKing.com"
socialAppearAtTop = true
socialAppearAtBottom = true
viewMorePostLink = "/blog/"

categoriesByCount = false
includeReadingTime = true
loadFavicon = false
faviconVersion = ""

[params.intro]
header = "Careless Lisper"
paragraph = "The rantings and ravings of a Computer Science student with an affinity for obscure programming languages"
about = "Ryan King is a student of Computer Science at Boston University, pursuing a combined MS/BA degree. This blog will be a chronicle of the remainder of his journey, and hopefully share a few of the lessons he learns along the way. The name of this blog, Careless Lisper, is a play on the name of the Lisp family of programming languages and the classic 80s hit, Careless Whisper by Wham."

[params.intro.pic]
src = "/img/portrait.jpg"
circle = true
imperfect = false
width = "160px"
alt = "Picture of Ryan King"

[params.postAmount]
sidebar = 2

[[menu.main]]
name = "Blog"
url = "/blog"
identifier = "fa fa-newspaper-o"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

[social]
github = "ryantking"
codepen = "ryantking"
flickr = "130602175@N03"
instagram = "thee_ryanking"
linkedin = "ryantking"
stackoverflow = "6391857"
twitter = "thee_ryanking"
email = "hello@ryanking.com"