baseurl = "http://ryanking.com/"
languageCode = "en-us"
theme = "future-imperfect"
title = "Careless Lisper"
preserveTaxonomyNames = true
paginate = 6
copyright = "&copy; 2016 Ryan King"
disqusShortname = "carelesslisper"
googleAnalytics = "UA-78435473-1"

[params]
description = "The rantings and ravings of a Software Engineer with an affinity for distributed systems and obscure programming languages"
navbarTitle = "RyanKing.com"
socialAppearAtTop = true
socialAppearAtBottom = true
viewMorePostLink = "/blog/"

categoriesByCount = false
includeReadingTime = true
loadFavicon = true
faviconVersion = ""

[params.intro]
header = "Careless Lisper"
paragraph = "The rantings and ravings of a Software Engineer with an affinity for distributed systems and obscure programming languages"
about = "Ryan King is a Software Engineer at Cogo Labs in Cambridge, MA with a BA in Computer Science from Boston University. In his free time he works on the development of the ATS ecoystem."

[params.intro.pic]
src = "/img/portrait.jpg"
circle = true
imperfect = false
width = "160px"
alt = "Picture of Ryan King"

[params.postAmount]
sidebar = 2

[[menu.main]]
name = "About"
url = "/about"
identifier = "fa fa-id-badge"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
identifier = "fa fa-newspaper-o"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
identifier = "fa fa-file-code-o"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
identifier = "fa fa-envelope-o"
weight = 4

[social]
linkedin = "ryantking"
github = "ryantking"
email = "hello@ryanking.com"
